__str__ don't die if a field has validity_between instead of validity_start.
Fixes an error that was occuring as one of the fields still referenced valid_between.

AttributeError: 'AdditionalCodeDescription' object has no attribute 'valid_between'

Add very basic test that checks every TrackedModel subclass, via @simonwo